-- V1: Initial schema baseline.
--
-- This reproduces the schema previously created by Hibernate's ddl-auto=update,
-- hand-authored so that constraints are explicitly named and reviewable.
-- Auto-generated DDL produced names like "fkc9d3qi2jq9yls5ob3xq86d1yg", which
-- are impossible to reference in a later migration or in an error message.
--
-- Known modelling defects are preserved here deliberately rather than silently
-- corrected, so that the corrective migrations that follow are real, reviewable
-- schema evolution. Each is flagged with the audit finding it corresponds to.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email      VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    -- Optimistic locking counter (@Version). NOT NULL with a default so rows
    -- inserted outside JPA still participate in version checks.
    version    BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- NOT NULL on email/username is stricter than the entity mapping was. It is
-- correct: both are already UNIQUE and both identify a user, but PostgreSQL
-- permits unlimited NULLs in a unique index -- so a nullable unique column does
-- not actually enforce "at most one user without an email". The database is the
-- last place this invariant can be guaranteed, so it is enforced here.

-- ---------------------------------------------------------------------------
-- properties
-- ---------------------------------------------------------------------------
CREATE TABLE properties (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR(255),
    address               VARCHAR(255),
    description           VARCHAR(255),
    -- NUMERIC(19,2), not Hibernate's default NUMERIC(38,2). 19 significant
    -- digits is far beyond any realistic nightly rate and matches the range of
    -- a BIGINT of cents, which keeps the value comfortably exact.
    base_price            NUMERIC(19, 2),
    max_guests            INTEGER,
    bedrooms              INTEGER,
    bathrooms             INTEGER,
    active                BOOLEAN,
    str_permit_number     VARCHAR(255),
    house_rules           TEXT,
    check_in_instructions TEXT,

    CONSTRAINT pk_properties PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- bookings
-- ---------------------------------------------------------------------------
CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    property_id       BIGINT,
    check_in          TIMESTAMP(6),
    check_out         TIMESTAMP(6),
    guest_name        VARCHAR(255),
    guest_email       VARCHAR(255),
    number_of_guests  INTEGER,
    total_price       NUMERIC(19, 2),
    occupancy_tax     NUMERIC(19, 2),
    status            VARCHAR(255),

    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_property FOREIGN KEY (property_id) REFERENCES properties (id)
);

-- ---------------------------------------------------------------------------
-- transactions
-- ---------------------------------------------------------------------------
CREATE TABLE transactions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- AUDIT H10: user_id is VARCHAR while users.id is BIGINT, and neither
    -- user_id nor property_id has a foreign key. A transaction can therefore
    -- reference a user or property that does not exist. Corrected in a later
    -- migration, which requires an accompanying entity change.
    user_id                VARCHAR(255) NOT NULL,
    property_id            BIGINT       NOT NULL,
    -- Denormalised copy of properties.name, written at transaction time.
    property_name          VARCHAR(255) NOT NULL,

    booking_id             BIGINT,
    booking_reference      VARCHAR(255),

    type                   VARCHAR(255) NOT NULL,
    category               VARCHAR(255) NOT NULL,
    subcategory            VARCHAR(255),
    description            VARCHAR(255) NOT NULL,

    -- AUDIT M4: DOUBLE PRECISION cannot represent decimal money exactly
    -- (0.1 + 0.2 = 0.30000000000000004). Summing these for a tax report
    -- accumulates error. Converted to NUMERIC in a later migration.
    transaction_amount     DOUBLE PRECISION NOT NULL,

    status                 VARCHAR(255),
    payment_method         VARCHAR(255),
    payment_reference      VARCHAR(255),

    recurring              BOOLEAN      NOT NULL DEFAULT FALSE,
    frequency              VARCHAR(255),

    vendor                 VARCHAR(255),
    receipt_url            VARCHAR(255),
    notes                  TEXT,

    -- Embedded TaxDetails
    tax_is_taxable         BOOLEAN,
    tax_category           VARCHAR(255),
    tax_amount             DOUBLE PRECISION,
    tax_is_deductible      BOOLEAN,
    tax_deduction_category VARCHAR(255),

    -- Embedded RefundInfo
    refund_amount          DOUBLE PRECISION,
    refund_date            TIMESTAMP(6),
    refund_reason          VARCHAR(255),
    refund_reference       VARCHAR(255),

    approval_status        VARCHAR(255),
    approved_by            VARCHAR(255),
    approved_date          TIMESTAMP(6),

    date                   TIMESTAMP(6) NOT NULL,
    due_date               TIMESTAMP(6),
    paid_at                TIMESTAMP(6),
    created_at             TIMESTAMP(6),
    updated_at             TIMESTAMP(6),

    CONSTRAINT pk_transactions PRIMARY KEY (id),

    -- Enum values are persisted as strings via @Enumerated(STRING). These CHECK
    -- constraints keep the database self-describing and reject values the
    -- application would not produce -- protection that survives direct SQL
    -- access, which application-level validation does not.
    CONSTRAINT ck_transactions_type CHECK (type IN ('EXPENSE', 'INCOME')),
    CONSTRAINT ck_transactions_status CHECK (status IN (
        'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'DISPUTED', 'REFUNDED')),
    CONSTRAINT ck_transactions_payment_method CHECK (payment_method IN (
        'CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'CHECK',
        'PAYPAL', 'VENMO', 'ZELLE', 'OTHER')),
    CONSTRAINT ck_transactions_frequency CHECK (frequency IN (
        'ONE_TIME', 'DAILY', 'WEEKLY', 'BI_WEEKLY', 'MONTHLY', 'QUARTERLY',
        'SEMI_ANNUALLY', 'ANNUALLY')),
    CONSTRAINT ck_transactions_category CHECK (category IN (
        'BOOKING_PAYMENT', 'CLEANING_FEE', 'SECURITY_DEPOSIT',
        'LATE_CHECKOUT_FEE', 'ADDITIONAL_GUEST_FEE', 'OTHER_INCOME',
        'CLEANING', 'MAINTENANCE', 'UTILITIES', 'SUPPLIES', 'INSURANCE',
        'MORTGAGE', 'PROPERTY_TAX', 'PLATFORM_FEES', 'MARKETING',
        'OTHER_EXPENSE', 'TAXES', 'HOA_FEES', 'REPAIRS', 'FURNISHING',
        'PROPERTY_MANAGEMENT', 'PERMITS_LICENSES', 'LEGAL_PROFESSIONAL'))
);

-- ---------------------------------------------------------------------------
-- Transaction element collections
-- ---------------------------------------------------------------------------
CREATE TABLE transaction_tags (
    transaction_id BIGINT NOT NULL,
    tag            VARCHAR(255),

    CONSTRAINT fk_transaction_tags_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);
-- No primary key: this maps a JPA List, whose semantics permit duplicate tags.
-- A (transaction_id, tag) primary key would silently change that behaviour.

CREATE TABLE transaction_warranties (
    transaction_id        BIGINT NOT NULL,
    warranty_start_date   TIMESTAMP(6),
    warranty_end_date     TIMESTAMP(6),
    warranty_description  VARCHAR(255),
    warranty_document_url VARCHAR(255),

    CONSTRAINT fk_transaction_warranties_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);

CREATE TABLE transaction_metadata (
    transaction_id BIGINT       NOT NULL,
    metadata_key   VARCHAR(255) NOT NULL,
    metadata_value VARCHAR(255),

    CONSTRAINT pk_transaction_metadata PRIMARY KEY (transaction_id, metadata_key)
);
ALTER TABLE transaction_metadata
    ADD CONSTRAINT fk_transaction_metadata_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
-- PostgreSQL creates an index for PRIMARY KEY and UNIQUE constraints, but NOT
-- for foreign keys. An unindexed FK column means every child lookup and every
-- parent DELETE (which must check for referencing rows) performs a sequential
-- scan of the child table.
--
-- Each index below backs a query the application actually issues. Indexes that
-- would merely look thorough are omitted: every index costs storage and slows
-- INSERT/UPDATE/DELETE, since it must be maintained inside the same transaction.

-- Loading a Transaction's collections issues WHERE transaction_id = ?, and
-- deleting a transaction must check each child table.
CREATE INDEX ix_transaction_tags_transaction_id
    ON transaction_tags (transaction_id);
CREATE INDEX ix_transaction_warranties_transaction_id
    ON transaction_warranties (transaction_id);
-- transaction_metadata needs no equivalent: its primary key is
-- (transaction_id, metadata_key), and the leading column of that composite
-- index already serves lookups by transaction_id.

-- Backs Booking -> Property navigation and DELETE checks on properties.
CREATE INDEX ix_bookings_property_id ON bookings (property_id);

-- Indexes supporting TransactionRepository.findByUserId / findByPropertyId are
-- intentionally NOT created here. Those columns are being retyped and given
-- foreign keys in a later migration, and an index created now would have to be
-- dropped and rebuilt. They arrive with that change.
